"""empty message

Revision ID: fdf63278d661
Revises: 895afd0a68d4
Create Date: 2022-08-22 11:11:57.007386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf63278d661'
down_revision = '895afd0a68d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('phone', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'Venue', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_column('Venue', 'phone')
    # ### end Alembic commands ###
